package com.example.fitnesstrackingapp.network;

/**
 * Vrste zahteva koje klijent može poslati serveru.
 */
public enum RequestType {

    PING,

    GET_ALL_EXERCISES,
    CREATE_EXERCISE,
    UPDATE_EXERCISE,
    DELETE_EXERCISE,

    GET_ALL_PLANS,
    CREATE_PLAN,
    UPDATE_PLAN,
    DELETE_PLAN,

    GET_PLAN_EXERCISES,
    ADD_EXERCISE_TO_PLAN,
    UPDATE_PLAN_EXERCISE,
    REMOVE_EXERCISE_FROM_PLAN,

    GET_ALL_SESSIONS,
    CREATE_SESSION,
    UPDATE_SESSION,
    DELETE_SESSION,

    GET_SESSION_EXERCISES,
    ADD_SESSION_EXERCISE,
    UPDATE_SESSION_EXERCISE,
    REMOVE_SESSION_EXERCISE,
    GET_WORKOUT_SUMMARY
}