package com.example.fitnesstrackingapp.network;

public enum RequestType {PING, GET_ALL_EXERCISES, CREATE_EXERCISE, UPDATE_EXERCISE,
    DELETE_EXERCISE, GET_ALL_PLANS, CREATE_PLAN, UPDATE_PLAN, DELETE_PLAN, GET_PLAN_EXERCISES, ADD_EXERCISE_TO_PLAN,
    UPDATE_PLAN_EXERCISE, REMOVE_EXERCISE_FROM_PLAN
}
